version: "3.8"
services:
  postman:
    build:
      context: .
      dockerfile: Dockerfile
    image: buzensb/newman:0.3
    volumes:
    - ".:/var/opt/newman/"
    entrypoint: /opt/launch_postman_collections.sh
