pipeline {
    agent {
        node {
            label 'docker'
        }
    }
    parameters {
        string(name: 'git_tool_url', defaultValue: 'https://gitlab.gie-sv.fr/outils/outilsvalidationdin/atlas/atlas_containers/docker_robotframework.git', description: 'URL to Test tool repository')
        string(name: 'git_tests_url', defaultValue: 'https://gitlab.gie-sv.fr/outils/outilsvalidationdin/gtc/idc/idc_smoke_tests.git', description: 'URL to tests repository?')
        string(name: 'almDomain', defaultValue: 'FORMATION', description:'Domaine ALM du projet de test')
        string(name: 'almProject', defaultValue: 'FORMATION', description:'Projet ALM de test vers lequel les résultats seront exportés')
        string(name: 'almTestFolder', defaultValue: 'TmpTest', description:'Dossier du Test Plan vers lequel les tests seront exportés')
        string(name: 'almTestSetFolder', defaultValue: 'TmpTestSet', description:'Dossier du Test Lab vers lequel les résultats seront exportés')
    }
    stages {
        stage('CleanWorkspace') {
            steps {
                cleanWs()
            }
        }
        stage('GetToolAndTests'){
            steps {
                git credentialsId: 'AD_GIE', url: "${params.git_tool_url}"
                stash name: "workspace", includes: "**"
                cleanWs()
                git credentialsId: 'AD_GIE', url: "${params.git_tests_url}"
                unstash name: "workspace"
            }
        }
        stage("Test") {
            steps {
                sh 'docker-compose up --build'
            }
        }
    }
    post {
        always {
            sh 'docker-compose down'
            archiveArtifacts artifacts: '**', followSymlinks: false
        }
        success {
            junit healthScaleFactor: 0.0, skipPublishingChecks: true, testResults: '**/junit_report.xml'
            uploadResultToALM almTimeout:'30', almDomain: "${params.almDomain}", almProject: "${params.almProject}", almServerName: 'QC GIE', almTestFolder: "${params.almTestFolder}", almTestSetFolder: "${params.almTestSetFolder}", clientType: 'MyClient', credentialsId: 'AD_GIE', jenkinsServerUrl: 'http://pc-buzensb.sesam.loc:8080', testingFramework: 'JUnit', testingResultFile: '**/junit_report.xml', testingTool: 'PyTest'
        }
    }
}
